### ISSUE TITLE
reformat.cpp::executeCutensor::388 checkMacros.cpp::catchCudaError::202

### ISSUE THREAD

**Issue by leslie27ch** [NVIDIA-AI-IOT/Lidar_AI_Solution#309]
Hello, I'm really at a loss here and would greatly appreciate your guidance:
I trained an epoch 2 model (using CUDA 11.3), performed PTQ quantization, and converted it to ONNX. When I built and ran it (using CUDA 11.6), everything was normal, and the result visualization was also fine.
Then, I used the epoch 6 model, and without changing anything else, I followed the same steps, but when I ran it (using CUDA 11.6), I encountered the following error. it lools error happened during transfusionhead forward。
![图片](https://github.com/user-attachments/assets/237d4f28-e9c0-4d89-9690-c9a8c3de1864)

**Comment by pacientes** [comment]
@leslie27ch have you solve it?

**Comment by leslie27ch** [comment]
> [@leslie27ch](https://github.com/leslie27ch) have you solve it?

I resolved the issue because when computing geometry in BEVPool, I made a mistake in modifying the "kept" condition. I originally intended not to calculate the area within 5 meters in front of and behind the ego vehicle (自车前后各5米范围), but the implementation logic was incorrect.
