### ISSUE TITLE
Support SM 120 (blackwell)

### ISSUE THREAD

**Issue by yuhang1008** [NVIDIA-AI-IOT/Lidar_AI_Solution#341]
Hi, author, thank for this great work.

I've run CUDA-bevfusion successfully on RTX3070, but when running on RTX 5080, I got this CUDA runtime error:

<img width="1482" height="558" alt="Image" src="https://github.com/user-attachments/assets/73037dfb-41e8-4c1c-920f-0fa1f9884649" />

It seems the root reason is the `libspconv` dosen't support GPU of sm=120 for now. I saw the recent commit says it support sm=110: https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/commit/d692b74265a6ebe309118f648acea5f871129afe

There are also some similar issues:
https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/issues/333
https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/issues/317

I'm appreciate if you can consider adding this support. It will be very helpful to the community. Thank you!

**Comment by dheepak-gan** [comment]
@yuhang1008 Hey Yuhang, it looks like you completed the BEVFusion inferencing steps on the RTX3070. I have a doubt regarding the LiDAR preprocessing steps. Could you please assist me with that? Also, please take a look at issue #342 . Thanks!

<img width="604" height="444" alt="Image" src="https://github.com/user-attachments/assets/cee54ede-e004-4246-809e-01558ca9dfb0" />
what the 1x5 actual mean.

**Comment by yuhang1008** [comment]
close this issue as problem has been solved by https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/commit/6d21564df2fe9d62153664f8a45d4ce516e1c9a3

**Comment by LaplaTom** [comment]
Hi, I find this problem too. I replaced libspconv.so of x86_64_cuda12.8 with libspconv.so of CUDA_CenterPoint, but can't build success. This report is it : 

In file included from /usr/local/TensorRT-8.6.1.6/include/NvInfer.h:17,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/tensorrt.cpp:26:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h: In member function ‘nvinfer1::ICudaEngine* nvinfer1::IRuntime::deserializeCudaEngine(const void*, std::size_t, nvinfer1::IPluginFactory*)’:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h:674:61: warning: unused parameter ‘pluginFactory’ [-Wunused-parameter]
  674 |         void const* blob, std::size_t size, IPluginFactory* pluginFactory) noexcept
      |                                             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /usr/local/TensorRT-8.6.1.6/include/NvInfer.h:17,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/include/centerpoint.h:27,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:24:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h: In member function ‘nvinfer1::ICudaEngine* nvinfer1::IRuntime::deserializeCudaEngine(const void*, std::size_t, nvinfer1::IPluginFactory*)’:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h:674:61: warning: unused parameter ‘pluginFactory’ [-Wunused-parameter]
  674 |         void const* blob, std::size_t size, IPluginFactory* pluginFactory) noexcept
      |                                             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp: In constructor ‘CenterPoint::CenterPoint(std::string, bool)’:
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:55:27: error: ‘load_engine_from_onnx’ is not a member of ‘spconv’
   55 |     scn_engine_ = spconv::load_engine_from_onnx("../model/centerpoint.scn.onnx");
      |                           ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/TensorRT-8.6.1.6/include/NvInfer.h:17,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/include/centerpoint.h:27,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/main.cpp:33:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h: In member function ‘nvinfer1::ICudaEngine* nvinfer1::IRuntime::deserializeCudaEngine(const void*, std::size_t, nvinfer1::IPluginFactory*)’:
/usr/local/TensorRT-8.6.1.6/include/NvInferRuntime.h:674:61: warning: unused parameter ‘pluginFactory’ [-Wunused-parameter]
  674 |         void const* blob, std::size_t size, IPluginFactory* pluginFactory) noexcept
      |                                             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp: In member function ‘int CenterPoint::doinfer(void*, unsigned int, cudaStream_t)’:
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:146:33: error: ‘spconv::DType’ has not been declared
  146 |         {valid_num, 5}, spconv::DType::Float16, d_voxel_features,
      |                                 ^~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:147:33: error: ‘spconv::DType’ has not been declared
  147 |         {valid_num, 4}, spconv::DType::Int32,   d_voxel_indices,
      |                                 ^~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:153:18: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const std::initializer_list<void*>&’
  153 |     trt_->forward({result->features_data(), d_reg_[0], d_height_[0], d_dim_[0], d_rot_[0], d_vel_[0], d_hm_[0],
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  154 |                                                 d_reg_[1], d_height_[1], d_dim_[1], d_rot_[1], d_vel_[1], d_hm_[1],
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  155 |                                                 d_reg_[2], d_height_[2], d_dim_[2], d_rot_[2], d_vel_[2], d_hm_[2],
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  156 |                                                 d_reg_[3], d_height_[3], d_dim_[3], d_rot_[3], d_vel_[3], d_hm_[3],
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  157 |                                                 d_reg_[4], d_height_[4], d_dim_[4], d_rot_[4], d_vel_[4], d_hm_[4],
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  158 |                                                 d_reg_[5], d_height_[5], d_dim_[5], d_rot_[5], d_vel_[5], d_hm_[5]}, stream);
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/include/centerpoint.h:33,
                 from /home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:24:
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/include/tensorrt.hpp:37:66: note:   initializing argument 1 of ‘virtual bool TensorRT::Engine::forward(const std::initializer_list<void*>&, void*)’
   37 |         virtual bool forward(const std::initializer_list<void*>& buffers, void* stream = nullptr) = 0;
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:204:37: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const unsigned int’ [-Wsign-compare]
  204 |                 if (max_keep_size++ < params_.nms_post_max_size) {
      |                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lcq/code/Lidar_AI_Solution/CUDA-CenterPoint/src/centerpoint.cpp:133:11: warning: unused variable ‘elapsedTime’ [-Wunused-variable]
  133 |     float elapsedTime = 0.0f;
      |           ^~~~~~~~~~~
make[2]: *** [CMakeFiles/centerpoint.dir/build.make:104：CMakeFiles/centerpoint.dir/src/centerpoint.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/centerpoint.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2

i ask Grok and it say because of the code were writed based on cuda11 and TensorRT 1.x, my device is RTX 5050 , cuda 12.8 and TensorRT 2.x. If i want to fix it, i need to modify code. I'm not sure if this is correct, could you please provide a suggested method?

**Comment by LaplaTom** [comment]
oh，sorry，my TensorRT is 8.6，spconv is 2.x
