### ISSUE TITLE
About Using Jetpark5.1.1 Image to Run BEVFusion on Orin

### ISSUE THREAD

**Issue by lwplw** [NVIDIA-AI-IOT/Lidar_AI_Solution#76]
Physical machine environment:

-Jetson AGX Orin
-Jetpark 5.0.2
-CUDA 11.4.2
-CuDNN 8.4.1.50
-TensorRT 8.4.1.5

Jetpark 5.1.1 environment:
-CUDA 11.4.19
-CuDNN 8.6.0
-TensorRT 8.5.2

I expect to install the Docker image of JetPark5.1.1 on Orin and configure the BEVFusion environment in the container. I first modified the path in reference #57 , but encountered issues with not being able to find libcuda.so and CUDA SM printing empty.

I referred to the solution in #71 and tried to skip the SM check, but then encountered more problems. I feel that continuing to modify it is not the correct approach.

May I ask if anyone has installed Docker on Orin and successfully run BEVFusion? Are there any other environment configuration tasks.

**Comment by lwplw** [comment]
The problem has been resolved due to a physical machine runtime configuration issue, which resulted in a series of subsequent errors. Bevfusion has successfully run.
